# Generated by Django 5.0.1 on 2024-02-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_comment_post_comment_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
